### ISSUE TITLE
Error caused by my re-naming in Mosaic Planner - Help!

### ISSUE THREAD

**Issue by jcornford** [fcollman/MosaicPlannerLive#13]
So I think two things of ZVIFrame were defined as edit_transform, but with varying use of words/captials, and due to my changes they now overwrite each other.

MosaicPlanner.py
line 1015 

``` python
self.edit_transform = options.Append(self.ID_EDIT_CAMERA_SETTINGS,'Edit Camera Properties...','Edit the size of the camera chip and the pixel size',kind=wx.ITEM_NORMAL)
```

line 1041 

``` python
self.Bind(wx.EVT_MENU, self.edit_transform, id=self.ID_EDITTRANSFORM)
```

line 1327  

``` python
def edit_transform(self,event):
        """event handler for clicking the edit transform menu button"""
        dlg = ChangeTransform(None, -1,title="Adjust Transform")
        dlg.ShowModal()
        #passes the settings to the position list
        #(pts_from,pts_to,transformType,flipVert,flipHoriz)=dlg.GetTransformInfo()
        #print transformType
```

I then get the following error:

``` python
Traceback (most recent call last):
  File "C:/AT/MosaicPlannerLive/MosaicPlanner.py", line 1353, in <module>
    frame = ZVISelectFrame(None,"Mosaic Planner")
  File "C:/AT/MosaicPlannerLive/MosaicPlanner.py", line 1041, in __init__
    self.Bind(wx.EVT_MENU, self.edit_transform, id=self.ID_EDITTRANSFORM)
  File "C:\Anaconda\lib\site-packages\wx-3.0-msw\wx\_core.py", line 4224, in Bind
    assert handler is None or callable(handler)
AssertionError
```

If I alter line 1015 self.edit_transform to a different name , this error goes away, but I get the following error when trying to snap an image: 

``` python
C:\Anaconda\lib\site-packages\matplotlib\axes\_base.py:2562: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=-11443.36, right=-11443.36
  'left=%s, right=%s') % (left, right))
C:\Anaconda\lib\site-packages\matplotlib\axes\_base.py:2809: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=-1583.74, top=-1583.74
  'bottom=%s, top=%s') % (bottom, top))
```

I guess this could be something unrelated, or the result of the loss line 1015 self.edit_transform. Any help would be appreciated ;]

**Comment by jcornford** [comment]
changed to 

``` python
self.edit_transform_option =  options.Append(self.ID_EDIT_CAMERA_SETTINGS,'Edit Camera Properties...','Edit the size of the camera chip and the pixel size',kind=wx.ITEM_NORMAL)
```

The other error is caused by incorrect objective configuration. Should add something to catch this for ease of use.
